env:
  browser: true
  commonjs: true
  es6: true
extends: 'eslint:recommended'
installedESLint: true
parserOptions:
  ecmaFeatures:
    experimentalObjectRestSpread: true
    jsx: true
  sourceType: module
plugins:
    - react
rules:
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi: off
#    - error
#    - never
  no-unused-vars: off
#    - error
#    -
#      varsIgnorePattern: 'React'
#      args: none
